import type { NetworkSettingsDraft } from './validate.js';
import { isSafePjsipIniValue } from './validate.js';

export type TransportRenderInput = Readonly<{
  settings: NetworkSettingsDraft;
  updatedAt?: string;
}>;

function renderTransportExtras(settings: NetworkSettingsDraft): readonly string[] | null {
  const out: string[] = [];
  if (settings.externalIp) {
    if (!isSafePjsipIniValue(settings.externalIp)) return null;
    out.push(`external_media_address=${settings.externalIp}`);
  }
  const sig = settings.externalSignalingIp ?? settings.externalIp;
  if (sig) {
    if (!isSafePjsipIniValue(sig)) return null;
    out.push(`external_signaling_address=${sig}`);
  }
  if (settings.localNet) {
    for (const cidr of settings.localNet.split(',').map((c) => c.trim()).filter(Boolean)) {
      if (!isSafePjsipIniValue(cidr)) return null;
      out.push(`local_net=${cidr}`);
    }
  }
  return out;
}

/** OpenPBX `/network` 相当の transports.conf 全文（endpoint テンプレ含む） */
export function renderPjsipTransportsConf(input: TransportRenderInput): string | null {
  const extras = renderTransportExtras(input.settings);
  if (extras === null) return null;
  const stamp = input.updatedAt ?? new Date().toISOString();
  const lines: string[] = [
    '; AUTO-GENERATED by denwa (/network). 手で編集しないこと。',
    `; updated_at: ${stamp}`,
    '',
    '[transport-udp]',
    'type=transport',
    'protocol=udp',
    'bind=0.0.0.0:5060',
    ...extras,
    '',
    '[transport-tcp]',
    'type=transport',
    'protocol=tcp',
    'bind=0.0.0.0:5060',
    ...extras,
    '',
    '[transport-wss]',
    'type=transport',
    'protocol=wss',
    'bind=0.0.0.0:8089',
    'cert_file=/etc/asterisk/certs/asterisk.pem',
    'priv_key_file=/etc/asterisk/certs/asterisk.key',
    ...extras,
    '',
    '[endpoint-internal](!)',
    'type=endpoint',
    'context=internal',
    'disallow=all',
    'allow=ulaw',
    'allow=alaw',
    'allow=opus',
    'media_encryption=sdes',
    'media_encryption_optimistic=no',
    'direct_media=no',
    'rtp_symmetric=yes',
    'force_rport=yes',
    'rewrite_contact=yes',
    '',
    '[endpoint-webrtc](!)',
    'type=endpoint',
    'context=internal',
    'disallow=all',
    'allow=opus',
    'allow=ulaw',
    'allow=alaw',
    'webrtc=yes',
    'use_avpf=yes',
    'media_use_received_transport=yes',
    'rtcp_mux=yes',
    'dtls_auto_generate_cert=yes',
    'dtls_verify=fingerprint',
    'ice_support=yes',
    'transport=transport-wss',
    'direct_media=no',
    'rtp_symmetric=yes',
    'force_rport=yes',
    'rewrite_contact=yes',
    '',
    '[auth-userpass](!)',
    'type=auth',
    'auth_type=userpass',
    '',
    '[aor-single](!)',
    'type=aor',
    'max_contacts=2',
    'remove_existing=yes',
    'qualify_frequency=30',
    '',
  ];
  return lines.join('\n');
}
