import type { IvrMenuDraft } from './types.js';

export function renderIvrDialplan(
  menus: readonly IvrMenuDraft[],
  opts?: { updatedAt?: string },
): string {
  const stamp = opts?.updatedAt ?? new Date().toISOString();
  const lines: string[] = [
    '; AUTO-GENERATED by OpenPBX.',
    `; updated_at: ${stamp}`,
    '',
    '[internal]',
  ];
  for (const m of menus) {
    lines.push(`exten => ${m.number},1,NoOp(IVR ${m.number} entry)`);
    lines.push(` same => n,Goto(ivr-${m.number},s,1)`);
  }
  lines.push('');

  for (const m of menus) {
    lines.push(`[ivr-${m.number}]`);
    lines.push('exten => s,1,Answer()');
    lines.push(' same => n,Wait(1)');
    if (m.welcomePrompt) lines.push(` same => n,Playback(${m.welcomePrompt})`);
    lines.push(' same => n,Set(IVR_TRIES=0)');
    lines.push(' same => n,Goto(menu,1)');
    lines.push('');
    lines.push('exten => menu,1,Set(IVR_TRIES=$[${IVR_TRIES} + 1])');
    lines.push(` same => n,GotoIf($[\${IVR_TRIES} > ${m.maxRetries}]?give-up)`);
    if (m.menuPrompt) lines.push(` same => n,Background(${m.menuPrompt})`);
    lines.push(` same => n,WaitExten(${m.waitSeconds})`);
    if (m.goodbyePrompt) {
      lines.push(` same => n(give-up),Playback(${m.goodbyePrompt})`);
    } else {
      lines.push(' same => n(give-up),NoOp(IVR give-up)');
    }
    lines.push(' same => n,Hangup()');
    lines.push('');
    for (const o of m.options) {
      lines.push(`exten => ${o.digit},1,NoOp(IVR ${m.number} option ${o.digit})`);
      if (o.action === 'goto_extension' && o.target) {
        lines.push(` same => n,Goto(internal,${o.target},1)`);
      } else if (o.action === 'goto_ringgroup' && o.target) {
        lines.push(` same => n,Goto(ringgroups,${o.target},1)`);
      } else {
        if (m.goodbyePrompt) lines.push(` same => n,Playback(${m.goodbyePrompt})`);
        lines.push(' same => n,Hangup()');
      }
      lines.push('');
    }
    const invalidPrompt = m.invalidPrompt;
    if (invalidPrompt) {
      lines.push(`exten => t,1,Playback(${invalidPrompt})`);
      lines.push(' same => n,Goto(menu,1)');
      lines.push(`exten => i,1,Playback(${invalidPrompt})`);
      lines.push(' same => n,Goto(menu,1)');
    } else {
      lines.push('exten => t,1,Goto(menu,1)');
      lines.push('exten => i,1,Goto(menu,1)');
    }
    lines.push('');
  }
  return lines.join('\n');
}
