export function renderPickupDialplan(opts?: { updatedAt?: string }): string {
  const stamp = opts?.updatedAt ?? new Date().toISOString();
  return [
    '; AUTO-GENERATED by OpenPBX.',
    `; updated_at: ${stamp}`,
    '',
    '[internal]',
    'exten => _*8,1,NoOp(Pickup attempt)',
    ' same => n,Pickup()',
    ' same => n,Hangup()',
    '',
  ].join('\n');
}
