import type { TrunkDraft } from './types.js';

export function renderTrunksDialplan(
  trunks: readonly TrunkDraft[],
  opts?: { updatedAt?: string },
): string {
  const stamp = opts?.updatedAt ?? new Date().toISOString();
  const lines: string[] = ['; AUTO-GENERATED by OpenPBX.', `; updated_at: ${stamp}`, '', '[from-trunk]'];
  for (const t of trunks) {
    if (t.didInbound) {
      lines.push(`exten => ${t.didInbound},1,NoOp(inbound from ${t.name})`);
      lines.push(` same => n,Goto(internal,${t.didInbound},1)`);
    }
  }
  lines.push('exten => _X.,1,NoOp(no inbound route)', ' same => n,Hangup()', '');
  if (trunks.some((t) => t.outboundPrefix)) {
    lines.push('[internal]');
    for (const t of trunks) {
      if (!t.outboundPrefix) continue;
      lines.push(`exten => _${t.outboundPrefix}X.,1,NoOp(outbound via ${t.name})`);
      lines.push(` same => n,Dial(PJSIP/\${EXTEN}@${t.name},60)`);
      lines.push(' same => n,Hangup()');
    }
    lines.push('');
  }
  return lines.join('\n');
}
