/** トランク未設定時の安全な空 conf（placeholder ではなく明示的ヘッダのみ） */

export function renderEmptyTrunksPjsip(updatedAt?: string): string {
  const stamp = updatedAt ?? new Date().toISOString();
  return [
    '; AUTO-GENERATED by denwa — no SIP trunks configured',
    `; updated_at: ${stamp}`,
    '; Add trunks at /trunks in the admin UI',
    '',
  ].join('\n');
}

export function renderEmptyTrunksDialplan(updatedAt?: string): string {
  const stamp = updatedAt ?? new Date().toISOString();
  return [
    '; AUTO-GENERATED by denwa — no trunk dialplan',
    `; updated_at: ${stamp}`,
    '',
    '[from-trunk]',
    'exten => _X.,1,Hangup()',
    '',
  ].join('\n');
}

export function isLegacyTrunkPlaceholder(text: string): boolean {
  return /;\s*placeholder\s*$/im.test(text) || /^;\s*AUTO-GENERATED placeholder\s*$/m.test(text);
}
