import type { TrunkDraft } from './types.js';
import { validateTrunkDraft } from './validate.js';

export function renderTrunksPjsip(
  trunks: readonly TrunkDraft[],
  opts?: { updatedAt?: string },
): string {
  const stamp = opts?.updatedAt ?? new Date().toISOString();
  const lines: string[] = ['; AUTO-GENERATED by OpenPBX.', `; updated_at: ${stamp}`, ''];
  for (const t of trunks) {
    lines.push(`; ---- trunk ${t.name} ----`);
    lines.push(`[${t.name}-auth]`, 'type=auth', 'auth_type=userpass');
    lines.push(`username=${t.username ?? ''}`, `password=${t.secret ?? ''}`, '');
    lines.push(`[${t.name}]`, 'type=aor', `contact=sip:${t.host}:${t.port}`, '');
    lines.push(`[${t.name}]`, 'type=endpoint', 'context=from-trunk', 'disallow=all', 'allow=ulaw', 'allow=alaw');
    lines.push(`outbound_auth=${t.name}-auth`, `aors=${t.name}`);
    if (t.fromUser) lines.push(`from_user=${t.fromUser}`);
    if (t.fromDomain) lines.push(`from_domain=${t.fromDomain}`);
    lines.push('rtp_symmetric=yes', 'force_rport=yes', 'rewrite_contact=yes', '');
    if (t.registration) {
      lines.push(`[${t.name}-reg]`, 'type=registration', `outbound_auth=${t.name}-auth`);
      lines.push(`server_uri=sip:${t.host}:${t.port}`);
      lines.push(`client_uri=sip:${t.username ?? ''}@${t.host}`);
      lines.push('retry_interval=60', 'forbidden_retry_interval=600', 'expiration=3600', '');
    }
    lines.push(`[${t.name}-identify]`, 'type=identify', `endpoint=${t.name}`, `match=${t.host}`, '');
  }
  return lines.join('\n');
}

export function renderTrunksPjsipIfValid(
  trunks: readonly TrunkDraft[],
  opts?: { updatedAt?: string },
): string | null {
  for (const t of trunks) {
    if (validateTrunkDraft(t).length > 0) return null;
  }
  return renderTrunksPjsip(trunks, opts);
}
