import type { ExtensionDraft } from './extension.js';
import {
  normalizeExtensionDraft,
  toExtensionDraft,
  validateExtensionDraft,
  type ExtensionDraftInput,
} from './extension.js';
import { sanitizeIniDisplayName } from './ini/sanitize.js';

/** Asterisk pjsip.d/extensions.conf 断片の純関数生成 */

export function renderPjsipExtensions(
  extensions: readonly ExtensionDraft[],
  opts?: { updatedAt?: string },
): string {
  const stamp = opts?.updatedAt ?? new Date().toISOString();
  const blocks: string[] = [
    '; AUTO-GENERATED by OpenPBX. 手で編集しないこと。',
    `; updated_at: ${stamp}`,
    '',
  ];
  for (const e of extensions) {
    const cidName = sanitizeIniDisplayName(e.displayName, `Ext ${e.number}`);
    const templateName = e.webrtc ? 'endpoint-webrtc' : 'endpoint-internal';
    blocks.push(`[${e.number}](${templateName})`);
    blocks.push(`auth=auth${e.number}`);
    blocks.push(`aors=${e.number}`);
    blocks.push(`callerid="${cidName}" <${e.number}>`);
    if (e.pickupGroupNames.length > 0) {
      const joined = e.pickupGroupNames.join(',');
      blocks.push(`named_call_group=${joined}`);
      blocks.push(`named_pickup_group=${joined}`);
    }
    blocks.push('');
    blocks.push(`[auth${e.number}](auth-userpass)`);
    blocks.push(`username=${e.number}`);
    blocks.push(`password=${e.secret}`);
    blocks.push('');
    blocks.push(`[${e.number}](aor-single)`);
    blocks.push('');
  }
  return blocks.join('\n');
}

/** T-PJSIP-005: いずれかが invalid なら conf を出力しない */
export function renderPjsipExtensionsIfValid(
  extensions: readonly ExtensionDraftInput[],
  opts?: { updatedAt?: string },
): string | null {
  for (const e of extensions) {
    if (validateExtensionDraft(e).length > 0) return null;
  }
  const branded = extensions.map((e) => toExtensionDraft(normalizeExtensionDraft(e)));
  return renderPjsipExtensions(branded, opts);
}
