export type RingStrategy = 'ringall' | 'linear';

export type RingGroupDraft = Readonly<{
  number: string;
  name: string | null;
  strategy: RingStrategy;
  ringSeconds: number;
  fallbackExtension: string | null;
  members: readonly string[];
}>;

const NUMBER_RE = /^[0-9]{2,6}$/;
const STRATEGIES = new Set<RingStrategy>(['ringall', 'linear']);

export function validateRingGroupDraft(draft: RingGroupDraft): string[] {
  const errs: string[] = [];
  if (!NUMBER_RE.test(draft.number)) errs.push('着信グループ番号は 2〜6 桁の数字');
  if (!STRATEGIES.has(draft.strategy)) errs.push(`未知の strategy: ${draft.strategy}`);
  if (!Number.isInteger(draft.ringSeconds) || draft.ringSeconds < 5 || draft.ringSeconds > 180) {
    errs.push('呼出時間は 5〜180 秒');
  }
  for (const m of draft.members) {
    if (!NUMBER_RE.test(m)) errs.push(`メンバー番号が不正: ${m}`);
  }
  if (draft.fallbackExtension && !NUMBER_RE.test(draft.fallbackExtension)) {
    errs.push('fallback も内線番号形式');
  }
  return errs;
}

export function renderRingGroupDialplan(
  groups: readonly RingGroupDraft[],
  opts?: { updatedAt?: string },
): string {
  const stamp = opts?.updatedAt ?? new Date().toISOString();
  const lines: string[] = [
    '; AUTO-GENERATED by OpenPBX. 手で編集しないこと。',
    `; updated_at: ${stamp}`,
    '',
    '[ringgroups]',
  ];
  if (groups.length === 0) lines.push('; (まだグループがありません)');

  for (const g of groups) {
    lines.push(`; --- ${g.number} ${g.name ?? ''} (${g.strategy}) ---`);
    if (g.members.length === 0) {
      lines.push(`exten => ${g.number},1,NoOp(empty ring group ${g.number})`);
      lines.push(' same => n,Playback(invalid)');
      lines.push(' same => n,Hangup()');
      lines.push('');
      continue;
    }
    if (g.strategy === 'ringall') {
      const dialString = g.members.map((m) => `PJSIP/${m}`).join('&');
      lines.push(`exten => ${g.number},1,NoOp(ring group ${g.number} ringall)`);
      lines.push(` same => n,Dial(${dialString},${g.ringSeconds},tTm)`);
      lines.push(
        g.fallbackExtension
          ? ` same => n,Goto(internal,${g.fallbackExtension},1)`
          : ' same => n,Hangup()',
      );
    } else {
      lines.push(`exten => ${g.number},1,NoOp(ring group ${g.number} linear)`);
      for (const m of g.members) {
        lines.push(` same => n,Dial(PJSIP/${m},${g.ringSeconds},tTm)`);
      }
      lines.push(
        g.fallbackExtension
          ? ` same => n,Goto(internal,${g.fallbackExtension},1)`
          : ' same => n,Hangup()',
      );
    }
    lines.push('');
  }
  return lines.join('\n');
}
