export type HolidayDraft = Readonly<{ date: string; name: string }>;
export type TimeRuleDialplan = Readonly<{
  name: string;
  days: string;
  startTime: string;
  endTime: string;
}>;

export function renderBusinessHoursDialplan(
  rules: readonly TimeRuleDialplan[],
  holidays: readonly HolidayDraft[],
  opts?: { updatedAt?: string },
): string {
  const stamp = opts?.updatedAt ?? new Date().toISOString();
  const lines: string[] = [
    '; AUTO-GENERATED by OpenPBX.',
    `; updated_at: ${stamp}`,
    '',
    '[businesshours]',
    'exten => s,1,NoOp(business hours check)',
    ' same => n,Set(TODAY=${STRFTIME(${EPOCH},,%Y-%m-%d)})',
  ];
  for (const h of holidays) {
    lines.push(` same => n,GotoIf($["${h.date}" = "\${TODAY}"]?closed)`);
  }
  for (const r of rules) {
    lines.push(` same => n,GotoIfTime(${r.startTime}-${r.endTime},${r.days},*,*?open)`);
  }
  lines.push(
    ' same => n,Set(BUSINESS_HOURS=closed)',
    ' same => n,Return()',
    ' same => n(open),Set(BUSINESS_HOURS=open)',
    ' same => n,Return()',
    ' same => n(closed),Set(BUSINESS_HOURS=closed)',
    ' same => n,Return()',
    '',
  );
  return lines.join('\n');
}
